[mypy]

# ToDo: enable the mypy_path to apply checking to PLAMS defined classes
# mypy_path = src
files = src
explicit_package_bases = True
namespace_packages = True
follow_imports = normal

ignore_missing_imports = True

warn_unused_ignores = False

# Start from idealistic strict standpoint...
strict = True

# ...Then disable functionality which is not yet passing
# See: https://mypy.readthedocs.io/en/stable/existing_code.html
disallow_subclassing_any = False
disallow_untyped_decorators = False
disallow_any_generics = False
disallow_untyped_calls = False
# disallow_incomplete_defs = False
# disallow_untyped_defs = False
no_implicit_reexport = False
warn_return_any = False

# Temporary excludes for files with with many tedious errors
exclude = ^src/scm/plams/(interfaces(/molecule/packmol.py|/thirdparty)|tools/(reaction.py|geometry.py)|mol|/pdbtools.py|recipes|scripts|trajectories)

# ToDo: use this style for excludes when enabling the mypy_path
# [mypy-scm.plams.interfaces.molecule.packmol]
# ignore_errors = True

# [mypy-scm.plams.interfaces.thirdparty.*]
# ignore_errors = True

# [mypy-scm.plams.tools.reaction]
# ignore_errors = True

# [mypy-scm.plams.tools.geometry]
# ignore_errors = True

# [mypy-scm.plams.mol.pdbtools]
# ignore_errors = True

# [mypy-scm.plams.recipes.*]
# ignore_errors = True

# [mypy-scm.plams.scripts.*]
# ignore_errors = True

# [mypy-scm.plams.trajectories.*]
# ignore_errors = True
