name: fix2024-auto-pr

on:
# Run on merging a PR into trunk
  pull_request:
    types:
      - closed
    branches:
      - DavidOrmrodMorley/fix-auto-pr # for testing

jobs:
  create-pr:
    # Only run if the PR was merged and contained the auto-fix2024 label
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'auto-fix2024')
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        run: |
          echo "Should run..."